"""IEC 61850 可编辑模型的应用服务。"""

from __future__ import annotations

from collections import Counter, OrderedDict, defaultdict
from collections.abc import Callable
from datetime import datetime
from functools import wraps
import json
import re
from threading import RLock
from typing import Any
import uuid

from sqlalchemy import delete, func, or_, select
from sqlalchemy.orm import Session

from src.data.controller.db import local_session
from src.data.model.iec61850_modeling import (
    Iec61850ModelProject,
    Iec61850ModelVersion,
)
from src.modeling.artifacts import build_artifact_bundle, list_file_variants, validate_file_variant
from src.modeling.catalog import (
    CHILD_RULES,
    KIND_LABELS,
    PROTECTED_KINDS,
    SINGLETON_CHILD_KINDS,
    get_kind_schema,
)
from src.modeling.cdc_templates import list_cdc_templates, materialize_cdc_template
from src.modeling.dataset_members import list_dataset_member_candidates
from src.modeling.document import ModelDocument, ModelNode, ModelReference
from src.modeling.effective_instance import build_effective_instance_tree
from src.modeling.parameterized_templates import (
    preview_lnode_do_generation,
)
from src.modeling.profiles import (
    list_profiles,
    logical_node_templates,
    profile_lock,
    resolve_profiles,
    service_capabilities,
)
from src.modeling.reference_options import contextualize_node_schema
from src.modeling.scl_importer import SclModelImporter, fcda_reference_name
from src.modeling.semantic_validation import validate_semantic_references
from src.modeling.standards import list_standards
import src.proto.iec61850.plugins.scl.validator.builtin_rules  # noqa: F401
from src.web.api.exceptions import ConflictError, NotFoundError, ValidationError

SessionFactory = Callable[[], Session]
NAME_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9_\-]{0,63}$")
LN_CLASS_PATTERN = re.compile(r"^[A-Z][A-Z0-9]{3}$")
REFERENCE_RELATION_LABELS = {
    "LN_TYPE": "逻辑节点类型引用",
    "DO_TYPE": "数据对象类型引用",
    "DA_TYPE": "数据属性类型引用",
    "ENUM_TYPE": "枚举类型引用",
    "CONTROL_DATASET": "控制块数据集引用",
    "CONNECTED_AP_IED": "访问点 IED 引用",
}


def _serialized_project_operation(method: Callable[..., Any]) -> Callable[..., Any]:
    """Serialize access to one cached mutable model document."""

    @wraps(method)
    def wrapper(self, project_id: str, *args: Any, **kwargs: Any) -> Any:
        with self._get_project_lock(project_id):
            return method(self, project_id, *args, **kwargs)

    return wrapper


def _json_loads(value: str | None) -> dict[str, Any]:
    if not value:
        return {}
    try:
        parsed = json.loads(value)
        return parsed if isinstance(parsed, dict) else {}
    except (TypeError, json.JSONDecodeError):
        return {}


def _json_dumps(value: dict[str, Any] | None) -> str:
    return json.dumps(value or {}, ensure_ascii=False, separators=(",", ":"))


def _iso(value: datetime | None) -> str | None:
    return value.isoformat() if value else None


class Iec61850ModelingService:
    """管理模型工程、节点树、影响分析和基础规则校验。"""

    _DOCUMENT_CACHE_SIZE = 4
    _DOCUMENT_CACHE_MAX_NODES = 50_000

    def __init__(self, session_factory: SessionFactory = local_session):
        self.session_factory = session_factory
        self._document_cache: OrderedDict[str, tuple[str, ModelDocument]] = OrderedDict()
        self._document_cache_lock = RLock()
        self._project_locks: dict[str, RLock] = {}
        self._project_locks_guard = RLock()

    def _get_project_lock(self, project_id: str) -> RLock:
        with self._project_locks_guard:
            return self._project_locks.setdefault(project_id, RLock())

    def _cache_document(self, cache_key: str, document: ModelDocument) -> None:
        with self._document_cache_lock:
            self._document_cache[document.project_id] = (cache_key, document)
            self._document_cache.move_to_end(document.project_id)
            while len(self._document_cache) > 1 and (
                len(self._document_cache) > self._DOCUMENT_CACHE_SIZE
                or sum(len(item[1].nodes) for item in self._document_cache.values()) > self._DOCUMENT_CACHE_MAX_NODES
            ):
                self._document_cache.popitem(last=False)

    @staticmethod
    def _require_project(session: Session, project_id: str) -> Iec61850ModelProject:
        project = session.get(Iec61850ModelProject, project_id)
        if not project:
            raise NotFoundError("模型工程不存在或已被删除")
        return project

    @staticmethod
    def _require_node(document: ModelDocument, node_id: str) -> ModelNode:
        node = document.get(node_id)
        if not node:
            raise NotFoundError("模型节点不存在或已被删除")
        return node

    @staticmethod
    def _normalize_legacy_fcda_names(document: ModelDocument) -> None:
        """Repair names generated by the old ``GGIO.1.DO..FC`` formatter."""

        for siblings in document.by_parent.values():
            fcda_nodes = [node for node in siblings if node.kind == "FCDA"]
            if not fcda_nodes:
                continue
            used_names = {
                node.name
                for node in fcda_nodes
                if not re.fullmatch(
                    re.escape(
                        ".".join(
                            str(node.attributes.get(key, "")) for key in ("lnClass", "lnInst", "doName", "daName", "fc")
                        ).strip(".")
                    )
                    + r"(?:_\d+)?",
                    node.name,
                )
            }
            for node in fcda_nodes:
                legacy_name = ".".join(
                    str(node.attributes.get(key, "")) for key in ("lnClass", "lnInst", "doName", "daName", "fc")
                ).strip(".")
                if not legacy_name or not re.fullmatch(
                    re.escape(legacy_name) + r"(?:_\d+)?",
                    node.name,
                ):
                    continue
                base = fcda_reference_name(node.attributes) or "FCDA"
                candidate = base
                suffix = 2
                while candidate in used_names:
                    candidate = f"{base}_{suffix}"
                    suffix += 1
                node.name = candidate
                used_names.add(candidate)

    @staticmethod
    def _materialize_inherited_instance_attributes(document: ModelDocument) -> None:
        """Upgrade older imported documents with effective q/t DOI children."""

        ln_types = {
            str(node.attributes.get("id") or node.name): node for node in document.nodes if node.kind == "LNODE_TYPE"
        }
        do_types = {
            str(node.attributes.get("id") or node.name): node for node in document.nodes if node.kind == "DO_TYPE"
        }
        for logical_node in list(document.nodes):
            if logical_node.kind not in ("LN0", "LN"):
                continue
            ln_type = ln_types.get(str(logical_node.attributes.get("lnType") or ""))
            if ln_type is None:
                continue
            do_definitions = {child.name: child for child in document.children(ln_type.id) if child.kind == "DO_DEF"}
            for doi in (child for child in document.children(logical_node.id) if child.kind == "DOI"):
                do_definition = do_definitions.get(doi.name)
                if do_definition is None:
                    continue
                type_id = str(do_definition.attributes.get("type") or "")
                do_type = do_types.get(type_id)
                if do_type is None:
                    continue
                definitions = {child.name: child for child in document.children(do_type.id) if child.kind == "DA_DEF"}
                existing = {child.name for child in document.children(doi.id) if child.kind == "DAI"}
                next_order = (
                    max(
                        (child.sort_order for child in document.children(doi.id)),
                        default=-1,
                    )
                    + 1
                )
                for name in ("q", "t"):
                    definition = definitions.get(name)
                    if definition is None or name in existing:
                        continue
                    document.add_node(
                        parent_id=doi.id,
                        kind="DAI",
                        name=name,
                        sort_order=next_order,
                        attributes={
                            "_templateInherited": True,
                            "sourceType": type_id,
                            "fc": definition.attributes.get("fc", ""),
                            "bType": definition.attributes.get("bType", ""),
                        },
                    )
                    existing.add(name)
                    next_order += 1

    def _load_document(self, project: Iec61850ModelProject) -> ModelDocument:
        cache_key = project.model_checksum or project.model_json or ""
        with self._document_cache_lock:
            cached = self._document_cache.get(project.id)
            if cached and cached[0] == cache_key:
                self._document_cache.move_to_end(project.id)
                return cached[1]
        try:
            document = ModelDocument.from_json(project.id, project.model_json)
        except (TypeError, ValueError, json.JSONDecodeError) as exc:
            raise ValidationError("模型文档损坏或格式不受支持") from exc

        self._normalize_legacy_fcda_names(document)
        self._materialize_inherited_instance_attributes(document)
        self._cache_document(cache_key, document)
        return document

    def _save_document(self, project: Iec61850ModelProject, document: ModelDocument) -> None:
        content = document.to_json()
        project.model_json = content
        project.model_format_version = document.FORMAT_VERSION
        project.model_node_count = len(document.nodes)
        project.model_checksum = document.checksum(content)
        self._cache_document(project.model_checksum, document)

    @staticmethod
    def _project_dict(project: Iec61850ModelProject, node_count: int | None = None) -> dict[str, Any]:
        result = {
            "id": project.id,
            "name": project.name,
            "code": project.code,
            "description": project.description,
            "file_type": project.file_type,
            "standard_version": project.standard_version,
            "namespace": project.namespace,
            "modeling_mode": project.modeling_mode,
            "status": project.status,
            "revision": project.revision,
            "validation_errors": project.validation_errors,
            "validation_warnings": project.validation_warnings,
            "created_at": _iso(project.created_at),
            "updated_at": _iso(project.updated_at),
        }
        result["node_count"] = project.model_node_count if node_count is None else node_count
        return result

    @staticmethod
    def _node_dict(node: ModelNode, *, child_count: int = 0) -> dict[str, Any]:
        return {
            "id": node.id,
            "project_id": node.project_id,
            "parent_id": node.parent_id,
            "kind": node.kind,
            "kind_label": KIND_LABELS.get(node.kind, node.kind),
            "name": node.name,
            "label": node.name,
            "sort_order": node.sort_order,
            "attributes": dict(node.attributes),
            "revision": node.revision,
            "child_count": child_count,
            "protected": node.kind in PROTECTED_KINDS or bool(node.attributes.get("_templateInherited")),
            "created_at": _iso(node.created_at),
            "updated_at": _iso(node.updated_at),
        }

    def list_projects(
        self,
        *,
        keyword: str = "",
        status: str = "",
        page: int = 1,
        page_size: int = 20,
    ) -> dict[str, Any]:
        with self.session_factory() as session:
            filters = []
            if keyword.strip():
                value = f"%{keyword.strip()}%"
                filters.append(or_(Iec61850ModelProject.name.like(value), Iec61850ModelProject.code.like(value)))
            if status.strip():
                filters.append(Iec61850ModelProject.status == status.upper())

            total = session.scalar(select(func.count(Iec61850ModelProject.id)).where(*filters)) or 0
            projects = session.scalars(
                select(Iec61850ModelProject)
                .where(*filters)
                .order_by(Iec61850ModelProject.updated_at.desc(), Iec61850ModelProject.name)
                .offset((page - 1) * page_size)
                .limit(page_size)
            ).all()
            return {
                "items": [self._project_dict(project) for project in projects],
                "total": total,
                "page": page,
                "page_size": page_size,
            }

    def create_project(self, payload: dict[str, Any]) -> dict[str, Any]:
        name = str(payload.get("name", "")).strip()
        code = str(payload.get("code", "")).strip()
        ied = payload.get("ied") or {}
        ied_name = str(ied.get("name", "")).strip()
        if not name:
            raise ValidationError("工程名称不能为空")
        if not NAME_PATTERN.fullmatch(code):
            raise ValidationError("工程编码需以字母开头，只能包含字母、数字、下划线和短横线")
        if not NAME_PATTERN.fullmatch(ied_name):
            raise ValidationError("IED 名称需以字母开头，只能包含字母、数字、下划线和短横线")

        logical_devices = payload.get("logical_devices") or [{"inst": "LD0", "desc": "默认逻辑设备"}]
        if not logical_devices:
            raise ValidationError("至少需要创建一个逻辑设备")
        logical_device_names = [str(item.get("inst", "")).strip() for item in logical_devices]
        if len(logical_device_names) != len(set(logical_device_names)):
            raise ConflictError("逻辑设备实例标识不能重复")

        try:
            profile_ids = resolve_profiles(payload.get("profiles"))
        except KeyError as exc:
            raise ValidationError(f"未知建模配置档：{exc}") from exc

        project_id = str(uuid.uuid4())
        with self.session_factory() as session, session.begin():
            if session.scalar(select(Iec61850ModelProject.id).where(Iec61850ModelProject.code == code)):
                raise ConflictError(f"工程编码 {code} 已存在")
            project = Iec61850ModelProject(
                id=project_id,
                name=name,
                code=code,
                description=str(payload.get("description", "")).strip(),
                file_type=str(payload.get("file_type", "ICD")).upper(),
                standard_version=str(payload.get("standard_version", "IEC 61850 Ed2.1")),
                namespace=str(payload.get("namespace", "")),
                modeling_mode="FROM_SCRATCH",
            )
            session.add(project)
            document = ModelDocument.empty(project_id)

            def add_node(
                kind: str,
                node_name: str,
                parent_id: str | None,
                attributes: dict[str, Any] | None = None,
                sort_order: int = 0,
            ) -> ModelNode:
                return document.add_node(
                    parent_id=parent_id,
                    kind=kind,
                    name=node_name,
                    attributes=attributes,
                    sort_order=sort_order,
                )

            root = add_node(
                "ROOT",
                name,
                None,
                {
                    "code": code,
                    "emitEdition": True,
                    "schemaLocation": "http://www.iec.ch/61850/2003/SCL SCL.xsd",
                    "profiles": profile_lock(profile_ids),
                },
            )
            add_node(
                "HEADER",
                "Header",
                root.id,
                {
                    "id": code,
                    "version": "1",
                    "revision": "1",
                    "nameStructure": "IEDName",
                    "toolID": "EMS Simulator IEC61850 Modeler",
                },
                0,
            )
            communication = add_node("COMMUNICATION", "Communication", root.id, {}, 5)
            subnet = add_node(
                "SUBNETWORK",
                "StationBus",
                communication.id,
                {"type": "8-MMS", "bitRate": 100, "multiplier": "M"},
                0,
            )
            ied_node = add_node(
                "IED",
                ied_name,
                root.id,
                {
                    "manufacturer": ied.get("manufacturer", ""),
                    "type": ied.get("type", ""),
                    "configVersion": ied.get("configVersion", "1.0"),
                    "desc": ied.get("desc", ""),
                },
                10,
            )
            services = add_node("SERVICES", "Services", ied_node.id, {}, 0)
            for index, (tag, capability_attrs) in enumerate(service_capabilities(profile_ids)):
                add_node(
                    "SERVICE_CAPABILITY",
                    tag,
                    services.id,
                    {"tag": tag, **capability_attrs},
                    index,
                )
            ap_name = str(payload.get("access_point_name", "AP1")).strip() or "AP1"
            access_point = add_node("ACCESS_POINT", ap_name, ied_node.id, {}, 10)
            server = add_node("SERVER", "Server", access_point.id, {}, 0)
            connected_ap = add_node(
                "CONNECTED_AP",
                f"{ied_name}_{ap_name}",
                subnet.id,
                {"iedName": ied_name, "apName": ap_name},
                0,
            )
            address = add_node("ADDRESS", "Address", connected_ap.id, {}, 0)
            for index, (parameter_type, value) in enumerate(
                (
                    ("IP", "192.168.1.10"),
                    ("IP-SUBNET", "255.255.255.0"),
                    ("IP-GATEWAY", "192.168.1.1"),
                    ("OSI-TSEL", "0001"),
                    ("OSI-SSEL", "0001"),
                    ("OSI-PSEL", "00000001"),
                )
            ):
                add_node("P", parameter_type, address.id, {"type": parameter_type, "value": value}, index)
            ln0_type_id = f"{code}_LLN0"
            ln_templates = logical_node_templates(profile_ids)
            for index, logical_device in enumerate(logical_devices):
                inst = str(logical_device.get("inst", "")).strip()
                if not NAME_PATTERN.fullmatch(inst):
                    raise ValidationError(f"逻辑设备实例 {inst or '(空)'} 格式不正确")
                ld = add_node(
                    "LDEVICE",
                    inst,
                    server.id,
                    {"inst": inst, "desc": logical_device.get("desc", "")},
                    index,
                )
                add_node(
                    "LN0",
                    "LLN0",
                    ld.id,
                    {"lnClass": "LLN0", "inst": "", "lnType": ln0_type_id},
                    0,
                )
                for template_index, template in enumerate(ln_templates, start=1):
                    ln_class = str(template["lnClass"])
                    ln_inst = str(template.get("inst") or "1")
                    prefix = str(template.get("prefix") or "")
                    add_node(
                        "LN",
                        f"{prefix}{ln_class}{ln_inst}",
                        ld.id,
                        {
                            "prefix": prefix,
                            "lnClass": ln_class,
                            "inst": ln_inst,
                            "lnType": f"{code}_{prefix}{ln_class}",
                            "desc": str(template.get("desc") or ""),
                        },
                        template_index,
                    )

            templates = add_node("DATA_TYPE_TEMPLATES", "DataTypeTemplates", root.id, {}, 20)
            add_node(
                "LNODE_TYPE",
                ln0_type_id,
                templates.id,
                {"id": ln0_type_id, "lnClass": "LLN0", "desc": "自动生成的 LLN0 基础类型"},
                0,
            )
            for index, template in enumerate(ln_templates, start=1):
                prefix = str(template.get("prefix") or "")
                ln_class = str(template["lnClass"])
                type_id = f"{code}_{prefix}{ln_class}"
                add_node(
                    "LNODE_TYPE",
                    type_id,
                    templates.id,
                    {"id": type_id, "lnClass": ln_class, "desc": str(template.get("desc") or "")},
                    index,
                )
            document.rebuild_references()
            self._save_document(project, document)

        return {"project": self._project_dict(project), "tree": self.get_tree(project_id)}

    @staticmethod
    def list_profiles() -> list[dict[str, Any]]:
        return list_profiles()

    @staticmethod
    def list_standards() -> list[dict[str, Any]]:
        return list_standards()

    @staticmethod
    def list_file_variants() -> list[dict[str, Any]]:
        return list_file_variants()

    @staticmethod
    def list_cdc_templates() -> list[dict[str, Any]]:
        return list_cdc_templates()

    @staticmethod
    def preview_import(
        content: bytes,
        *,
        filename: str,
        progress: Callable[[str, int, int, str], None] | None = None,
        cancel_check: Callable[[], None] | None = None,
    ) -> dict[str, Any]:
        try:
            imported = SclModelImporter().parse(
                content,
                filename=filename,
                progress=progress,
                cancel_check=cancel_check,
            )
        except ValueError as exc:
            raise ValidationError(str(exc)) from exc
        return {"project": imported.project, "summary": imported.summary, "warnings": imported.warnings}

    def import_scl(
        self,
        content: bytes,
        *,
        filename: str,
        code: str = "",
        name: str = "",
    ) -> dict[str, Any]:
        try:
            imported = SclModelImporter().parse(content, filename=filename)
        except ValueError as exc:
            raise ValidationError(str(exc)) from exc
        project_data = imported.project
        target_code = (code or project_data["code"]).strip()
        target_name = (name or project_data["name"]).strip()
        if not NAME_PATTERN.fullmatch(target_code):
            raise ValidationError("导入工程编码格式不正确")
        project_id = str(uuid.uuid4())
        with self.session_factory() as session, session.begin():
            if session.scalar(select(Iec61850ModelProject.id).where(Iec61850ModelProject.code == target_code)):
                raise ConflictError(f"工程编码 {target_code} 已存在")
            project = Iec61850ModelProject(
                id=project_id,
                name=target_name,
                code=target_code,
                description=f"从 {filename} 导入",
                file_type=project_data["file_type"],
                standard_version=project_data["standard_version"],
                namespace=project_data["namespace"],
                modeling_mode="IMPORTED",
                status="DRAFT",
            )
            session.add(project)
            document = ModelDocument.empty(project_id)
            for item in imported.nodes:
                document.add_node(
                    node_id=item["id"],
                    parent_id=item["parent_id"],
                    kind=item["kind"],
                    name=item["name"],
                    sort_order=item["sort_order"],
                    attributes=item["attributes"],
                )
            document.rebuild_references()
            self._save_document(project, document)

        return {
            "project": self.get_project(project_id),
            "summary": imported.summary,
            "warnings": imported.warnings,
        }

    def get_project(self, project_id: str) -> dict[str, Any]:
        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            # Keep project metadata reads independent of model size. The tree
            # endpoint already supplies node kinds to the workspace, so parsing
            # a multi-megabyte document here only duplicates startup work.
            return self._project_dict(project)

    @_serialized_project_operation
    def delete_project(self, project_id: str) -> None:
        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            session.execute(delete(Iec61850ModelVersion).where(Iec61850ModelVersion.project_id == project_id))
            session.delete(project)
        with self._document_cache_lock:
            self._document_cache.pop(project_id, None)

    @_serialized_project_operation
    def get_tree(
        self,
        project_id: str,
        *,
        compact: bool = False,
        max_depth: int | None = None,
        focus_id: str = "",
        keyword: str = "",
        kind: str = "",
    ) -> list[dict[str, Any]]:
        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            emitted_kind_labels: set[str] = set()
            focus_ancestors: set[str] = set()
            focus_node = document.get(focus_id) if focus_id else None
            while focus_node is not None:
                focus_ancestors.add(focus_node.id)
                focus_node = document.get(focus_node.parent_id) if focus_node.parent_id else None
            normalized_keyword = keyword.strip().lower()
            normalized_kind = kind.strip().upper()
            lnode_type_data_objects = {
                str(node.attributes.get("id") or node.name): {
                    child.name for child in document.children(node.id) if child.kind == "DO_DEF"
                }
                for node in document.nodes
                if node.kind == "LNODE_TYPE"
            }

            def displayed_child_count(
                node: ModelNode,
                children: list[ModelNode],
            ) -> int:
                if node.kind not in {"LN0", "LN"}:
                    return len(children)
                template_names = lnode_type_data_objects.get(
                    str(node.attributes.get("lnType") or ""),
                    set(),
                )
                non_data_count = sum(child.kind != "DOI" for child in children)
                extra_instances = sum(child.kind == "DOI" and child.name not in template_names for child in children)
                return non_data_count + len(template_names) + extra_instances

            filtered_ids: set[str] | None = None
            if normalized_keyword or normalized_kind:
                filtered_ids = set()
                for candidate in document.nodes:
                    matches_keyword = not normalized_keyword or (
                        normalized_keyword in candidate.name.lower() or normalized_keyword in candidate.kind.lower()
                    )
                    matches_kind = not normalized_kind or candidate.kind == normalized_kind
                    if not (matches_keyword and matches_kind):
                        continue
                    current: ModelNode | None = candidate
                    while current is not None and current.id not in filtered_ids:
                        filtered_ids.add(current.id)
                        current = document.get(current.parent_id) if current.parent_id else None

            def build(node: ModelNode, parent_path: str = "", depth: int = 0) -> dict[str, Any]:
                node_children = document.children(node.id)
                effective_child_count = displayed_child_count(
                    node,
                    node_children,
                )
                visible_children = (
                    node_children
                    if filtered_ids is None
                    else [child for child in node_children if child.id in filtered_ids]
                )
                if compact and depth > 1:
                    result = {
                        "id": node.id,
                        "parent_id": node.parent_id,
                        "kind": node.kind,
                        "name": node.name,
                        "child_count": effective_child_count,
                    }
                    if node.kind not in emitted_kind_labels:
                        result["kind_label"] = KIND_LABELS.get(node.kind, node.kind)
                    if node.kind == "EXTENSION" and "lossRisk" in node.attributes:
                        result["attributes"] = {"lossRisk": node.attributes["lossRisk"]}
                    path = ""
                else:
                    result = self._node_dict(
                        node,
                        child_count=effective_child_count,
                    )
                    if compact:
                        result["detail_loaded"] = depth == 0
                    path = f"{parent_path}/{node.name}" if parent_path else node.name
                    if not compact:
                        result["path"] = path
                emitted_kind_labels.add(node.kind)
                should_expand = (
                    filtered_ids is not None or max_depth is None or depth < max_depth or node.id in focus_ancestors
                )
                if should_expand:
                    result["children"] = [build(child, path, depth + 1) for child in visible_children]
                    if len(visible_children) < len(node_children) or effective_child_count != len(node_children):
                        result["children_partial"] = True
                return result

            roots = document.children(None)
            if filtered_ids is not None:
                roots = [root for root in roots if root.id in filtered_ids]
            return [build(root) for root in roots]

    @_serialized_project_operation
    def get_node(
        self,
        project_id: str,
        node_id: str,
        *,
        include_children: bool = False,
    ) -> dict[str, Any]:
        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            node = self._require_node(document, node_id)
            node_children = document.children(node.id)
            child_count = len(node_children)
            if node.kind in {"LN0", "LN"}:
                ln_type_id = str(node.attributes.get("lnType") or "")
                ln_type = next(
                    (
                        candidate
                        for candidate in document.nodes
                        if candidate.kind == "LNODE_TYPE"
                        and str(candidate.attributes.get("id") or candidate.name) == ln_type_id
                    ),
                    None,
                )
                if ln_type is not None:
                    template_names = {child.name for child in document.children(ln_type.id) if child.kind == "DO_DEF"}
                    child_count = (
                        sum(child.kind != "DOI" for child in node_children)
                        + len(template_names)
                        + sum(child.kind == "DOI" and child.name not in template_names for child in node_children)
                    )
            result = self._node_dict(node, child_count=child_count)
            result["schema"] = contextualize_node_schema(document, node, get_kind_schema(node.kind))
            result["path"] = document.node_path(node)
            result["detail_loaded"] = True
            if include_children:
                result["children"] = [
                    {
                        **self._node_dict(
                            child,
                            child_count=len(document.children(child.id)),
                        ),
                        "detail_loaded": False,
                    }
                    for child in document.children(node.id)
                ]
            return result

    @_serialized_project_operation
    def get_effective_instance_tree(
        self,
        project_id: str,
        logical_node_id: str,
    ) -> dict[str, Any]:
        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            logical_node = self._require_node(document, logical_node_id)
            if logical_node.kind not in {"LN0", "LN"}:
                raise ValidationError("只有 LN0 或 LN 可以展开类型模板数据模型")
            return build_effective_instance_tree(document, logical_node)

    @_serialized_project_operation
    def get_lnode_type_options(
        self,
        project_id: str,
        *,
        ln_class: str = "",
    ) -> list[dict[str, Any]]:
        """Return business-facing LNodeType choices with inherited model counts."""

        normalized_class = ln_class.strip().upper()
        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            options: list[dict[str, Any]] = []
            for lnode_type in document.nodes:
                if lnode_type.kind != "LNODE_TYPE":
                    continue
                type_id = str(lnode_type.attributes.get("id") or lnode_type.name)
                declared_class = str(lnode_type.attributes.get("lnClass") or "").upper()
                if normalized_class and declared_class != normalized_class:
                    continue
                preview_node = ModelNode(
                    id=f"lnode-type-preview:{lnode_type.id}",
                    project_id=project_id,
                    parent_id=None,
                    kind="LN0" if declared_class == "LLN0" else "LN",
                    name="LLN0" if declared_class == "LLN0" else f"{declared_class}1",
                    attributes={
                        "lnType": type_id,
                        "lnClass": declared_class,
                        "inst": "" if declared_class == "LLN0" else "1",
                    },
                )
                effective = build_effective_instance_tree(
                    document,
                    preview_node,
                )
                options.append(
                    {
                        "node_id": lnode_type.id,
                        "id": type_id,
                        "name": lnode_type.name,
                        "lnClass": declared_class,
                        "description": str(lnode_type.attributes.get("desc") or ""),
                        "data_objects": effective["summary"]["data_objects"],
                        "data_attributes": effective["summary"]["data_attributes"],
                        "warnings": effective["warnings"],
                    }
                )
            options.sort(
                key=lambda item: (
                    item["lnClass"],
                    item["id"],
                )
            )
            return options

    @_serialized_project_operation
    def create_instance_override(
        self,
        project_id: str,
        logical_node_id: str,
        template_path: str,
        *,
        expected_project_revision: int | None = None,
    ) -> dict[str, Any]:
        normalized_path = template_path.strip(". ")
        if not normalized_path:
            raise ValidationError("模板路径不能为空")

        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            if expected_project_revision is not None and project.revision != expected_project_revision:
                raise ConflictError("模型已被其他操作修改，请刷新类型模板后重试")
            document = self._load_document(project)
            logical_node = self._require_node(document, logical_node_id)
            if logical_node.kind not in {"LN0", "LN"}:
                raise ValidationError("实例覆盖只能创建在 LN0 或 LN 下")

            effective = build_effective_instance_tree(
                document,
                logical_node,
            )
            if not effective["resolved"]:
                raise ValidationError("当前逻辑节点的 LNodeType 无法解析")

            target_chain: list[dict[str, Any]] | None = None

            def find_target(
                nodes: list[dict[str, Any]],
                ancestors: list[dict[str, Any]],
            ) -> None:
                nonlocal target_chain
                for candidate in nodes:
                    chain = [*ancestors, candidate]
                    if candidate.get("template_path") == normalized_path:
                        target_chain = chain
                        return
                    find_target(candidate.get("children") or [], chain)
                    if target_chain is not None:
                        return

            find_target(effective["nodes"], [])
            if target_chain is None:
                raise ValidationError(f"类型模板中不存在路径：{normalized_path}")
            if not target_chain[-1].get("inherited"):
                raise ValidationError("该节点不是类型模板继承节点")

            current_parent = logical_node
            changed_nodes: list[ModelNode] = []
            for effective_node in target_chain:
                expected_kind = str(effective_node.get("kind") or "")
                if expected_kind not in {"DOI", "SDI", "DAI"}:
                    raise ValidationError(f"不支持物化的实例节点类型：{expected_kind}")
                if not effective_node.get("virtual"):
                    actual = document.get(str(effective_node["id"]))
                    if actual is None or actual.parent_id != current_parent.id:
                        raise ConflictError("实例覆盖结构已变化，请刷新后重试")
                    current_parent = actual
                    continue

                same_name = next(
                    (
                        child
                        for child in document.children(current_parent.id)
                        if child.name == effective_node["name"] and child.kind in {"DOI", "SDI", "DAI"}
                    ),
                    None,
                )
                if same_name is not None:
                    if same_name.kind != expected_kind:
                        raise ConflictError(f"{same_name.name} 已存在，但实例节点类型不是 {expected_kind}")
                    if same_name.attributes.get("_templateInherited"):
                        same_name.attributes = {
                            key: value
                            for key, value in same_name.attributes.items()
                            if key
                            not in {
                                "_templateInherited",
                                "sourceType",
                                "fc",
                                "bType",
                            }
                        }
                        same_name.revision += 1
                        changed_nodes.append(same_name)
                    current_parent = same_name
                    continue

                current_parent = document.add_node(
                    parent_id=current_parent.id,
                    kind=expected_kind,
                    name=str(effective_node["name"]),
                    sort_order=int(effective_node.get("sort_order") or 0),
                    attributes={},
                )
                changed_nodes.append(current_parent)

            if changed_nodes:
                project.revision += 1
                project.status = "DRAFT"
                document.rebuild_references()
                self._save_document(project, document)

            result_node = self._node_dict(
                current_parent,
                child_count=len(document.children(current_parent.id)),
            )
            result_node["schema"] = contextualize_node_schema(
                document,
                current_parent,
                get_kind_schema(current_parent.kind),
            )
            result_node["path"] = document.node_path(current_parent)
            result_node["detail_loaded"] = True
            return {
                "logical_node_id": logical_node.id,
                "template_path": normalized_path,
                "node": result_node,
                "created_count": len(changed_nodes),
                "project_revision": project.revision,
            }

    @_serialized_project_operation
    def get_lnode_do_template_options(
        self,
        project_id: str,
        lnode_type_id: str,
    ) -> dict[str, Any]:
        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            lnode_type = self._require_node(document, lnode_type_id)
            if lnode_type.kind != "LNODE_TYPE":
                raise ValidationError("参数化 DO 模板只能应用到 LNodeType")
            do_types = [
                {
                    "id": str(node.attributes.get("id") or node.name),
                    "name": node.name,
                    "cdc": str(node.attributes.get("cdc") or ""),
                    "description": str(node.attributes.get("desc") or ""),
                }
                for node in document.nodes
                if node.kind == "DO_TYPE"
            ]
            do_types.sort(key=lambda item: (item["cdc"], item["id"]))
            return {
                "target": {
                    "id": lnode_type.id,
                    "name": lnode_type.name,
                    "lnClass": str(lnode_type.attributes.get("lnClass") or ""),
                },
                "do_types": do_types,
            }

    @_serialized_project_operation
    def preview_lnode_do_template(
        self,
        project_id: str,
        lnode_type_id: str,
        payload: dict[str, Any],
    ) -> dict[str, Any]:
        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            lnode_type = self._require_node(document, lnode_type_id)
            try:
                result = preview_lnode_do_generation(
                    document,
                    lnode_type,
                    name_pattern=str(payload.get("name_pattern") or ""),
                    start_index=int(payload.get("start_index", 1)),
                    quantity=int(payload.get("quantity", 1)),
                    index_width=int(payload.get("index_width", 3)),
                    do_type_ref=str(payload.get("do_type_ref") or ""),
                )
            except ValueError as exc:
                raise ValidationError(str(exc)) from exc
            result["project_revision"] = project.revision
            return result

    @_serialized_project_operation
    def apply_lnode_do_template(
        self,
        project_id: str,
        lnode_type_id: str,
        payload: dict[str, Any],
    ) -> dict[str, Any]:
        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            expected_revision = payload.get("expected_project_revision")
            if expected_revision is not None and project.revision != int(expected_revision):
                raise ConflictError("模型已被其他操作修改，请重新预览模板后再应用")
            document = self._load_document(project)
            lnode_type = self._require_node(document, lnode_type_id)
            try:
                preview = preview_lnode_do_generation(
                    document,
                    lnode_type,
                    name_pattern=str(payload.get("name_pattern") or ""),
                    start_index=int(payload.get("start_index", 1)),
                    quantity=int(payload.get("quantity", 1)),
                    index_width=int(payload.get("index_width", 3)),
                    do_type_ref=str(payload.get("do_type_ref") or ""),
                )
            except ValueError as exc:
                raise ValidationError(str(exc)) from exc
            if preview["summary"]["conflict"]:
                raise ConflictError(f"存在 {preview['summary']['conflict']} 个同名异构 DO，请调整名称格式或起始序号")

            max_order = max(
                (child.sort_order for child in document.children(lnode_type.id) if child.kind == "DO_DEF"),
                default=0,
            )
            created: list[ModelNode] = []
            for item in preview["items"]:
                if item["action"] != "CREATE":
                    continue
                max_order += 10
                created.append(
                    document.add_node(
                        parent_id=lnode_type.id,
                        kind="DO_DEF",
                        name=item["name"],
                        sort_order=max_order,
                        attributes=dict(item["attributes"]),
                    )
                )

            if created:
                lnode_type.revision += 1
                project.revision += 1
                project.status = "DRAFT"
                document.rebuild_references()
                self._save_document(project, document)
            return {
                "target_id": lnode_type.id,
                "created": [
                    {
                        **self._node_dict(node),
                        "path": document.node_path(node),
                    }
                    for node in created
                ],
                "created_count": len(created),
                "kept_count": preview["summary"]["keep"],
                "project_revision": project.revision,
            }

    @_serialized_project_operation
    def get_tree_kinds(self, project_id: str) -> list[dict[str, Any]]:
        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            counts: dict[str, int] = {}
            for node in document.nodes:
                counts[node.kind] = counts.get(node.kind, 0) + 1
            return [
                {
                    "kind": kind,
                    "label": KIND_LABELS.get(kind, kind),
                    "count": count,
                    "lossy_count": (
                        sum(
                            1
                            for node in document.nodes
                            if node.kind == kind and node.attributes.get("lossRisk") in (True, 1, "1", "true")
                        )
                        if kind == "EXTENSION"
                        else 0
                    ),
                }
                for kind, count in sorted(counts.items())
            ]

    @_serialized_project_operation
    def create_node(self, project_id: str, payload: dict[str, Any]) -> dict[str, Any]:
        parent_id = str(payload.get("parent_id", ""))
        kind = str(payload.get("kind", "")).upper()
        name = str(payload.get("name", "")).strip()
        if not name:
            raise ValidationError("节点名称不能为空")
        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            parent = self._require_node(document, parent_id)
            if kind not in CHILD_RULES.get(parent.kind, ()):
                parent_label = KIND_LABELS.get(parent.kind, parent.kind)
                child_label = KIND_LABELS.get(kind, kind)
                raise ValidationError(f"{parent_label} 下不能添加 {child_label}")
            attributes = dict(payload.get("attributes") or {})
            if kind in {"LN0", "LN"}:
                ln_type_id = str(attributes.get("lnType") or "")
                lnode_type = next(
                    (
                        item
                        for item in document.nodes
                        if item.kind == "LNODE_TYPE" and str(item.attributes.get("id") or item.name) == ln_type_id
                    ),
                    None,
                )
                if lnode_type is None:
                    raise ValidationError("新增逻辑节点时必须选择有效的 LNodeType")
                declared_class = str(lnode_type.attributes.get("lnClass") or "")
                actual_class = "LLN0" if kind == "LN0" else str(attributes.get("lnClass") or "")
                if declared_class and actual_class != declared_class:
                    raise ValidationError(
                        f"逻辑节点类 {actual_class or '（空）'} 与模板 {ln_type_id} 声明的 {declared_class} 不一致"
                    )
                attributes["lnType"] = ln_type_id
                attributes["lnClass"] = actual_class
            if kind in {"DOI", "SDI", "DAI"}:
                instance_path = [name]
                logical_node = parent
                while logical_node.kind not in {"LN0", "LN"}:
                    if logical_node.kind in {"DOI", "SDI"}:
                        instance_path.insert(0, logical_node.name)
                    if not logical_node.parent_id:
                        break
                    logical_node = self._require_node(
                        document,
                        logical_node.parent_id,
                    )
                matched: dict[str, Any] | None = None
                if logical_node.kind in {"LN0", "LN"}:
                    effective = build_effective_instance_tree(
                        document,
                        logical_node,
                    )
                    candidates = effective["nodes"]
                    for path_part in instance_path:
                        matched = next(
                            (item for item in candidates if item["name"] == path_part),
                            None,
                        )
                        if matched is None:
                            break
                        candidates = matched.get("children") or []
                if matched is None or matched["kind"] != kind:
                    raise ValidationError("实例数据节点必须对应类型模板路径，请从继承节点创建实例覆盖")
            siblings = document.children(parent_id)
            if any(item.kind == kind and item.name == name for item in siblings):
                raise ConflictError("同一父节点下已存在同类型、同名节点")
            if kind in SINGLETON_CHILD_KINDS and any(item.kind == kind for item in siblings):
                raise ConflictError(f"每个父节点只能包含一个 {KIND_LABELS.get(kind, kind)}")
            max_order = max((item.sort_order for item in siblings), default=0)
            requested_order = payload.get("sort_order")
            node = document.add_node(
                parent_id=parent_id,
                kind=kind,
                name=name,
                attributes=attributes,
                sort_order=int(requested_order if requested_order is not None else max_order + 10),
            )
            project.revision += 1
            project.status = "DRAFT"
            document.rebuild_references()
            self._save_document(project, document)
            result = self._node_dict(node)
            result["schema"] = get_kind_schema(kind)
            result["path"] = document.node_path(node)
            return result

    @_serialized_project_operation
    def get_dataset_member_candidates(
        self,
        project_id: str,
        dataset_id: str,
    ) -> dict[str, Any]:
        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            dataset = self._require_node(document, dataset_id)
            if dataset.kind != "DATASET":
                raise ValidationError("批量选择成员只能用于 DataSet 节点")
            try:
                return list_dataset_member_candidates(document, dataset)
            except ValueError as exc:
                raise ValidationError(str(exc)) from exc

    @_serialized_project_operation
    def create_dataset_members(
        self,
        project_id: str,
        dataset_id: str,
        candidate_ids: list[str],
        ordered_candidate_ids: list[str] | None = None,
    ) -> dict[str, Any]:
        if not candidate_ids and ordered_candidate_ids is None:
            raise ValidationError("请至少选择一个 DataSet 成员")
        if len(candidate_ids) > 5000 or len(ordered_candidate_ids or []) > 5000:
            raise ValidationError("单次最多保存 5000 个 FCDA")

        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            dataset = self._require_node(document, dataset_id)
            if dataset.kind != "DATASET":
                raise ValidationError("批量选择成员只能用于 DataSet 节点")

            discovery = list_dataset_member_candidates(document, dataset)
            candidates = {item["id"]: item for item in discovery["candidates"]}
            unique_ids = list(dict.fromkeys(candidate_ids))
            ordered_ids = list(dict.fromkeys(ordered_candidate_ids)) if ordered_candidate_ids is not None else None
            requested_ids = list(dict.fromkeys([*unique_ids, *(ordered_ids or [])]))
            unknown = [candidate_id for candidate_id in requested_ids if candidate_id not in candidates]
            if unknown:
                raise ValidationError(f"有 {len(unknown)} 个候选成员已失效，请刷新 DataModel 后重试")

            existing_keys = {item["id"] for item in discovery["candidates"] if item["existing"]}
            siblings = document.children(dataset.id)
            used_names = {item.name for item in siblings if item.kind == "FCDA"}
            next_order = max(
                (item.sort_order for item in siblings),
                default=0,
            )
            created: list[ModelNode] = []
            nodes_by_candidate_id: dict[str, ModelNode] = {}
            for member in discovery["existing_members"]:
                candidate_id = member.get("candidate_id")
                if candidate_id and candidate_id not in nodes_by_candidate_id:
                    nodes_by_candidate_id[candidate_id] = self._require_node(
                        document,
                        member["node_id"],
                    )
            skipped: list[str] = []
            for candidate_id in unique_ids:
                if candidate_id in existing_keys:
                    skipped.append(candidate_id)
                    continue
                attributes = dict(candidates[candidate_id]["attributes"])
                base_name = fcda_reference_name(attributes) or "FCDA"
                name = base_name
                suffix = 2
                while name in used_names:
                    name = f"{base_name}_{suffix}"
                    suffix += 1
                next_order += 10
                node = document.add_node(
                    parent_id=dataset.id,
                    kind="FCDA",
                    name=name,
                    attributes=attributes,
                    sort_order=next_order,
                )
                used_names.add(name)
                created.append(node)
                nodes_by_candidate_id[candidate_id] = node

            reordered_count = 0
            if ordered_ids is not None:
                ordered_nodes = [
                    nodes_by_candidate_id[candidate_id]
                    for candidate_id in ordered_ids
                    if candidate_id in nodes_by_candidate_id
                ]
                ordered_node_ids = {node.id for node in ordered_nodes}
                remaining_nodes = [
                    node for node in [*siblings, *created] if node.kind == "FCDA" and node.id not in ordered_node_ids
                ]
                for index, node in enumerate(
                    [*ordered_nodes, *remaining_nodes],
                    start=1,
                ):
                    sort_order = index * 10
                    if node.sort_order != sort_order:
                        node.sort_order = sort_order
                        node.revision += 1
                        reordered_count += 1

            if created or reordered_count:
                project.revision += 1
                project.status = "DRAFT"
                document.rebuild_references()
                self._save_document(project, document)
            return {
                "dataset_id": dataset.id,
                "created": [
                    {
                        **self._node_dict(node),
                        "path": document.node_path(node),
                    }
                    for node in created
                ],
                "created_count": len(created),
                "skipped_count": len(skipped),
                "skipped_candidate_ids": skipped,
                "reordered_count": reordered_count,
                "project_revision": project.revision,
            }

    @_serialized_project_operation
    def repair_dataset_member(
        self,
        project_id: str,
        dataset_id: str,
        fcda_id: str,
        candidate_id: str,
    ) -> dict[str, Any]:
        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            dataset = self._require_node(document, dataset_id)
            fcda = self._require_node(document, fcda_id)
            if dataset.kind != "DATASET" or fcda.kind != "FCDA" or fcda.parent_id != dataset.id:
                raise ValidationError("待修复节点不是该 DataSet 的 FCDA 成员")

            discovery = list_dataset_member_candidates(document, dataset)
            candidate = next(
                (item for item in discovery["candidates"] if item["id"] == candidate_id),
                None,
            )
            if candidate is None:
                raise ValidationError("替代候选项已失效，请刷新 DataModel 后重试")
            if candidate["existing"] and candidate["existing_node_id"] != fcda.id:
                raise ConflictError("该 FCDA 引用已经存在于当前 DataSet")

            attributes = dict(candidate["attributes"])
            base_name = fcda_reference_name(attributes) or "FCDA"
            used_names = {
                item.name for item in document.children(dataset.id) if item.kind == "FCDA" and item.id != fcda.id
            }
            name = base_name
            suffix = 2
            while name in used_names:
                name = f"{base_name}_{suffix}"
                suffix += 1
            fcda.name = name
            fcda.attributes_json = _json_dumps(attributes)
            fcda.revision += 1
            project.revision += 1
            project.status = "DRAFT"
            document.rebuild_references()
            self._save_document(project, document)
            return {
                **self._node_dict(fcda),
                "path": document.node_path(fcda),
                "project_revision": project.revision,
            }

    @_serialized_project_operation
    def update_node(self, project_id: str, node_id: str, payload: dict[str, Any]) -> dict[str, Any]:
        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            node = self._require_node(document, node_id)
            if node.attributes.get("_templateInherited"):
                raise ValidationError("类型继承的数据属性为只读，请在对应 DOType 中修改")
            expected_revision = payload.get("expected_revision")
            if expected_revision is not None and int(expected_revision) != node.revision:
                raise ConflictError("该节点已被其他操作修改，请刷新后重试", {"current_revision": node.revision})
            name = str(payload.get("name", node.name)).strip()
            if not name:
                raise ValidationError("节点名称不能为空")
            if name != node.name and any(
                item.id != node.id and item.kind == node.kind and item.name == name
                for item in document.children(node.parent_id)
            ):
                raise ConflictError("同一父节点下已存在同类型、同名节点")
            node.name = name
            if "attributes" in payload:
                node.attributes_json = _json_dumps(payload.get("attributes"))
            if "sort_order" in payload and payload["sort_order"] is not None:
                node.sort_order = int(payload["sort_order"])
            node.revision += 1
            project.revision += 1
            project.status = "DRAFT"
            if node.kind == "ROOT":
                project.name = name
            document.rebuild_references()
            self._save_document(project, document)
            result = self._node_dict(node)
            result["schema"] = get_kind_schema(node.kind)
            result["path"] = document.node_path(node)
            return result

    @_serialized_project_operation
    def apply_cdc_template(self, project_id: str, do_type_id: str, template_id: str) -> dict[str, Any]:
        """Merge a declarative CDC template into one DOType as a single project revision."""

        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            do_type = self._require_node(document, do_type_id)
            if do_type.kind != "DO_TYPE":
                raise ValidationError("CDC 模板只能应用到数据对象类型 DOType")
            do_type_attrs = _json_loads(do_type.attributes_json)
            existing = [node for node in document.children(do_type.id) if node.kind == "DA_DEF"]
            existing_payload = [{"name": node.name, **_json_loads(node.attributes_json)} for node in existing]
            try:
                template = materialize_cdc_template(
                    template_id,
                    do_type_name=str(do_type_attrs.get("id") or do_type.name),
                    cdc=str(do_type_attrs.get("cdc") or ""),
                    existing_attributes=existing_payload,
                )
            except KeyError as exc:
                raise ValidationError(f"未知 CDC 模板：{template_id}") from exc
            except ValueError as exc:
                raise ValidationError(str(exc)) from exc

            created: list[dict[str, str]] = []
            preserved: list[str] = []
            conflicts: list[dict[str, Any]] = []
            changed = False
            resolved_cdc = str(template.get("resolved_cdc") or "")
            if resolved_cdc and not do_type_attrs.get("cdc"):
                do_type_attrs["cdc"] = resolved_cdc
                do_type.attributes_json = _json_dumps(do_type_attrs)
                do_type.revision += 1
                changed = True

            existing_by_name = {node.name: node for node in existing}
            max_order = max((node.sort_order for node in existing), default=0)
            for index, definition in enumerate(template.get("attributes", []), start=1):
                name = str(definition["name"])
                attributes = {key: value for key, value in definition.items() if key != "name"}
                current = existing_by_name.get(name)
                if current:
                    current_attrs = _json_loads(current.attributes_json)
                    mismatches = {
                        key: {"current": current_attrs.get(key), "template": attributes.get(key)}
                        for key in ("bType", "fc", "type")
                        if attributes.get(key) not in (None, "") and current_attrs.get(key) != attributes.get(key)
                    }
                    if mismatches:
                        conflicts.append({"name": name, "fields": mismatches})
                    else:
                        preserved.append(name)
                    continue
                document.add_node(
                    parent_id=do_type.id,
                    kind="DA_DEF",
                    name=name,
                    sort_order=max_order + index * 10,
                    attributes=attributes,
                )
                created.append({"kind": "DA_DEF", "name": name})
                changed = True

            for dependency in template.get("dependencies", []):
                dependency_kind = str(dependency.get("kind") or "")
                dependency_id = str(dependency.get("id") or "")
                target = next(
                    (
                        node
                        for node in document.children(do_type.parent_id)
                        if node.kind == dependency_kind and str(node.attributes.get("id") or node.name) == dependency_id
                    ),
                    None,
                )
                if target is None:
                    sibling_order = max(
                        (node.sort_order for node in document.children(do_type.parent_id)),
                        default=0,
                    )
                    target = document.add_node(
                        parent_id=do_type.parent_id,
                        kind=dependency_kind,
                        name=dependency_id,
                        sort_order=sibling_order + 10,
                        attributes={"id": dependency_id},
                    )
                    created.append({"kind": dependency_kind, "name": dependency_id})
                    changed = True
                dependency_children = {node.name: node for node in document.children(target.id)}
                child_order = max((node.sort_order for node in dependency_children.values()), default=0)
                for child_index, child in enumerate(dependency.get("children", []), start=1):
                    child_name = str(child["name"])
                    if child_name in dependency_children:
                        preserved.append(f"{dependency_id}.{child_name}")
                        continue
                    child_kind = str(child["kind"])
                    child_attrs = {key: value for key, value in child.items() if key not in {"kind", "name"}}
                    document.add_node(
                        parent_id=target.id,
                        kind=child_kind,
                        name=child_name,
                        sort_order=child_order + child_index * 10,
                        attributes=child_attrs,
                    )
                    created.append({"kind": child_kind, "name": f"{dependency_id}.{child_name}"})
                    changed = True

            if changed:
                project.revision += 1
                project.status = "DRAFT"
                document.rebuild_references()
                self._save_document(project, document)
            return {
                "template_id": template_id,
                "do_type_id": do_type.id,
                "cdc": str(do_type_attrs.get("cdc") or resolved_cdc),
                "primary_fc": template["primary_fc"],
                "created": created,
                "preserved": sorted(set(preserved)),
                "conflicts": conflicts,
                "changed": changed,
                "project_revision": project.revision,
            }

    @_serialized_project_operation
    def get_delete_impact(self, project_id: str, node_id: str) -> dict[str, Any]:
        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            node = self._require_node(document, node_id)
            subtree = set(document.subtree_ids(node_id))
            inbound = [
                reference
                for reference in document.references
                if reference.target_node_id in subtree and reference.source_node_id not in subtree
            ]
            outbound_count = sum(reference.source_node_id in subtree for reference in document.references)
            protected = node.kind in PROTECTED_KINDS or bool(node.attributes.get("_templateInherited"))

            def endpoint_payload(node_id: str) -> dict[str, Any]:
                endpoint = document.get(node_id)
                if endpoint is None:
                    return {
                        "id": node_id,
                        "kind": "",
                        "kind_label": "未知节点",
                        "name": "已删除节点",
                        "path": "",
                    }
                return {
                    "id": endpoint.id,
                    "kind": endpoint.kind,
                    "kind_label": KIND_LABELS.get(
                        endpoint.kind,
                        endpoint.kind,
                    ),
                    "name": endpoint.name,
                    "path": document.node_path(endpoint),
                }

            return {
                "node": self._node_dict(node),
                "subtree_count": len(subtree),
                "descendant_count": max(0, len(subtree) - 1),
                "inbound_references": [
                    {
                        "id": ref.id,
                        "source_node_id": ref.source_node_id,
                        "target_node_id": ref.target_node_id,
                        "relation_type": ref.relation_type,
                        "relation_label": REFERENCE_RELATION_LABELS.get(
                            ref.relation_type,
                            ref.relation_type,
                        ),
                        "reference_value": str(ref.attributes.get("external_ref") or ""),
                        "source": endpoint_payload(ref.source_node_id),
                        "target": endpoint_payload(ref.target_node_id),
                    }
                    for ref in inbound
                ],
                "outbound_reference_count": outbound_count,
                "protected": protected,
                "can_delete": not protected and not inbound,
                "blocking_reason": (
                    "IEC 61850 必需结构节点不可删除"
                    if protected
                    else ("存在外部节点引用，请先解除引用" if inbound else "")
                ),
            }

    @_serialized_project_operation
    def delete_node(self, project_id: str, node_id: str, *, force: bool = False) -> dict[str, Any]:
        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            node = self._require_node(document, node_id)
            if node.kind in PROTECTED_KINDS or node.attributes.get("_templateInherited"):
                raise ValidationError("IEC 61850 必需结构节点不可删除")
            subtree = set(document.subtree_ids(node_id))
            inbound_count = sum(
                reference.target_node_id in subtree and reference.source_node_id not in subtree
                for reference in document.references
            )
            if inbound_count and not force:
                raise ConflictError("节点仍被其他配置引用，请先解除引用或确认强制删除")
            deleted_count = document.remove_subtree(node_id)
            project.revision += 1
            project.status = "DRAFT"
            self._save_document(project, document)
            return {"deleted_node_id": node_id, "deleted_count": deleted_count}

    @_serialized_project_operation
    def rebuild_references(self, project_id: str) -> dict[str, int]:
        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            count = document.rebuild_references()
            self._save_document(project, document)
            return {"reference_count": count}

    @_serialized_project_operation
    def validate_project(self, project_id: str) -> dict[str, Any]:
        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            document = self._load_document(project)
            nodes = document.nodes
            by_kind = Counter(node.kind for node in nodes)
            by_parent: dict[str | None, list[ModelNode]] = defaultdict(list)
            for node in nodes:
                by_parent[node.parent_id].append(node)
            issues: list[dict[str, Any]] = []
            type_ids: dict[str, set[str]] = defaultdict(set)
            for item in nodes:
                if item.kind in ("LNODE_TYPE", "DO_TYPE", "DA_TYPE", "ENUM_TYPE"):
                    type_attrs = _json_loads(item.attributes_json)
                    type_ids[item.kind].add(str(type_attrs.get("id") or item.name))
            ied_names = {item.name for item in nodes if item.kind == "IED"}
            datasets_by_parent = {
                parent_id: {item.name for item in siblings if item.kind == "DATASET"}
                for parent_id, siblings in by_parent.items()
            }

            def add(level: str, code: str, message: str, node: ModelNode | None = None, field: str = ""):
                issues.append(
                    {
                        "level": level,
                        "rule_code": code,
                        "node_id": node.id if node else None,
                        "path": document.node_path(node) if node else project.name,
                        "field": field,
                        "message": message,
                    }
                )

            for required_kind in ("ROOT", "HEADER", "COMMUNICATION", "IED", "DATA_TYPE_TEMPLATES"):
                if not by_kind[required_kind]:
                    add("ERROR", f"STRUCTURE_{required_kind}_REQUIRED", f"缺少必需节点：{KIND_LABELS[required_kind]}")
            for singleton_kind in ("ROOT", "HEADER", "DATA_TYPE_TEMPLATES"):
                if by_kind[singleton_kind] > 1:
                    add(
                        "ERROR",
                        f"STRUCTURE_{singleton_kind}_SINGLETON",
                        f"模型中只能包含一个{KIND_LABELS[singleton_kind]}",
                    )
            for variant_issue in validate_file_variant(list(nodes), project.file_type, for_publish=False):
                add("ERROR", variant_issue["code"], variant_issue["message"])
            if not by_kind["LDEVICE"]:
                add("ERROR", "STRUCTURE_LDEVICE_REQUIRED", "至少需要一个逻辑设备")

            for node in nodes:
                attrs = _json_loads(node.attributes_json)
                if not node.name.strip():
                    add("ERROR", "NAME_REQUIRED", "节点名称不能为空", node, "name")
                for field_schema in get_kind_schema(node.kind)["fields"]:
                    key = field_schema["key"]
                    if field_schema.get("required") and key != "name" and attrs.get(key) in (None, ""):
                        add(
                            "ERROR",
                            "FIELD_REQUIRED",
                            f"{field_schema['label']}不能为空",
                            node,
                            key,
                        )
                if node.kind == "LDEVICE" and not NAME_PATTERN.fullmatch(str(attrs.get("inst", ""))):
                    add("ERROR", "LDEVICE_INST_INVALID", "逻辑设备 inst 格式不正确", node, "inst")
                if node.kind == "LN":
                    ln_class = str(attrs.get("lnClass", ""))
                    if not LN_CLASS_PATTERN.fullmatch(ln_class):
                        add("ERROR", "LN_CLASS_INVALID", "逻辑节点类应为 4 位大写字母或数字", node, "lnClass")
                    if attrs.get("inst") in (None, ""):
                        add("ERROR", "LN_INST_REQUIRED", "逻辑节点实例号不能为空", node, "inst")
                if node.kind in ("REPORT_CONTROL", "GSE_CONTROL", "SAMPLED_VALUE_CONTROL") and not attrs.get("datSet"):
                    add("ERROR", "CONTROL_DATASET_REQUIRED", "控制块必须引用数据集", node, "datSet")
                if node.kind in ("LNODE_TYPE", "DO_TYPE", "DA_TYPE", "ENUM_TYPE") and not attrs.get("id"):
                    add("ERROR", "TYPE_ID_REQUIRED", "类型定义 ID 不能为空", node, "id")
                if node.kind in ("LN0", "LN"):
                    ln_type = str(attrs.get("lnType") or "")
                    if ln_type and ln_type not in type_ids["LNODE_TYPE"]:
                        add("ERROR", "LNODE_TYPE_REFERENCE_MISSING", f"逻辑节点类型 {ln_type} 不存在", node, "lnType")
                if node.kind in ("DO_DEF", "SDO_DEF"):
                    type_ref = str(attrs.get("type") or "")
                    if type_ref and type_ref not in type_ids["DO_TYPE"]:
                        add("ERROR", "DO_TYPE_REFERENCE_MISSING", f"数据对象类型 {type_ref} 不存在", node, "type")
                if node.kind in ("DA_DEF", "BDA_DEF") and attrs.get("bType") in ("Struct", "Enum"):
                    type_ref = str(attrs.get("type") or "")
                    target_kind = "DA_TYPE" if attrs.get("bType") == "Struct" else "ENUM_TYPE"
                    if not type_ref:
                        add("ERROR", "NESTED_TYPE_REQUIRED", "Struct/Enum 基础类型必须填写类型引用", node, "type")
                    elif type_ref not in type_ids[target_kind]:
                        add("ERROR", "NESTED_TYPE_REFERENCE_MISSING", f"引用的类型 {type_ref} 不存在", node, "type")
                if node.kind == "DA_DEF" and node.name in {"q", "t", "dU"}:
                    b_type = str(attrs.get("bType") or "")
                    fc = str(attrs.get("fc") or "")
                    if node.name == "q":
                        if b_type != "Quality":
                            add("ERROR", "CDC_Q_BTYPE_INVALID", "品质属性 q 的 bType 必须为 Quality", node, "bType")
                        if attrs.get("qchg") is not True:
                            add("WARNING", "CDC_Q_QCHG_RECOMMENDED", "品质属性 q 建议启用 qchg", node, "qchg")
                    elif node.name == "t" and b_type not in {"Timestamp", "TimeStamp"}:
                        add("ERROR", "CDC_T_BTYPE_INVALID", "时间戳属性 t 的 bType 必须为 Timestamp", node, "bType")
                    elif node.name == "dU":
                        if b_type != "Unicode255":
                            add(
                                "ERROR",
                                "CDC_DU_BTYPE_INVALID",
                                "数据描述属性 dU 的 bType 必须为 Unicode255",
                                node,
                                "bType",
                            )
                        if fc != "DC":
                            add("ERROR", "CDC_DU_FC_INVALID", "数据描述属性 dU 的 FC 必须为 DC", node, "fc")
                    if node.name in {"q", "t"}:
                        primary_fc = next(
                            (
                                str(_json_loads(sibling.attributes_json).get("fc") or "")
                                for sibling in by_parent.get(node.parent_id, [])
                                if sibling.kind == "DA_DEF"
                                and sibling.name in {"stVal", "mag", "instMag", "actVal", "mxVal", "setVal"}
                                and _json_loads(sibling.attributes_json).get("fc")
                            ),
                            "",
                        )
                        if primary_fc and fc != primary_fc:
                            add(
                                "ERROR",
                                "CDC_COMMON_FC_MISMATCH",
                                f"属性 {node.name} 的 FC 应与主值一致（{primary_fc}）",
                                node,
                                "fc",
                            )
                if node.kind in ("REPORT_CONTROL", "GSE_CONTROL", "SAMPLED_VALUE_CONTROL"):
                    dataset = str(attrs.get("datSet") or "")
                    if dataset and dataset not in datasets_by_parent.get(node.parent_id, set()):
                        add(
                            "ERROR",
                            "CONTROL_DATASET_MISSING",
                            f"引用的数据集 {dataset} 不存在于当前逻辑节点",
                            node,
                            "datSet",
                        )
                if node.kind == "CONNECTED_AP":
                    ied_name = str(attrs.get("iedName") or "")
                    if ied_name and ied_name not in ied_names:
                        add(
                            "ERROR",
                            "CONNECTED_AP_IED_MISSING",
                            f"通信配置引用的 IED {ied_name} 不存在",
                            node,
                            "iedName",
                        )
                if node.kind == "EXTENSION":
                    add(
                        "ERROR" if attrs.get("lossRisk") else "WARNING",
                        "LOSSY_EXTENSION_BLOCKED" if attrs.get("lossRisk") else "PRESERVED_EXTENSION_READ_ONLY",
                        (
                            "该扩展已确认存在有损风险，修复或明确保真策略前不能发布"
                            if attrs.get("lossRisk")
                            else "该节点为保真扩展片段；修改其父结构前请确认厂商兼容性"
                        ),
                        node,
                    )

            for logical_device in (node for node in nodes if node.kind == "LDEVICE"):
                ln0_count = sum(child.kind == "LN0" for child in by_parent.get(logical_device.id, []))
                if ln0_count != 1:
                    add("ERROR", "LN0_EXACTLY_ONE", "每个逻辑设备必须且只能包含一个 LLN0", logical_device)

            for ied in (node for node in nodes if node.kind == "IED"):
                services_nodes = [child for child in by_parent.get(ied.id, []) if child.kind == "SERVICES"]
                if len(services_nodes) != 1:
                    add("ERROR", "IED_SERVICES_EXACTLY_ONE", "每个 IED 必须且只能包含一个 Services", ied)
                    continue
                capability_names = {
                    str(_json_loads(child.attributes_json).get("tag") or child.name)
                    for child in by_parent.get(services_nodes[0].id, [])
                    if child.kind == "SERVICE_CAPABILITY"
                }
                ied_descendants = set(document.subtree_ids(ied.id))
                ied_nodes = [item for item in nodes if item.id in ied_descendants]
                if (
                    any(item.kind == "REPORT_CONTROL" for item in ied_nodes)
                    and "ConfReportControl" not in capability_names
                ):
                    add(
                        "ERROR",
                        "SERVICES_REPORT_CAPABILITY_MISSING",
                        "模型包含报告控制块，但 Services 未声明 ConfReportControl",
                        services_nodes[0],
                    )
                if any(item.kind == "GSE_CONTROL" for item in ied_nodes) and "GOOSE" not in capability_names:
                    add(
                        "ERROR",
                        "SERVICES_GOOSE_CAPABILITY_MISSING",
                        "模型包含 GOOSE 控制块，但 Services 未声明 GOOSE",
                        services_nodes[0],
                    )
                if any(item.kind == "SAMPLED_VALUE_CONTROL" for item in ied_nodes) and "SMVsc" not in capability_names:
                    add(
                        "ERROR",
                        "SERVICES_SMV_CAPABILITY_MISSING",
                        "模型包含采样值控制块，但 Services 未声明 SMVsc",
                        services_nodes[0],
                    )

            for siblings in by_parent.values():
                seen: set[tuple[str, str]] = set()
                for node in siblings:
                    key = (node.kind, node.name)
                    if key in seen:
                        add("ERROR", "SIBLING_NAME_DUPLICATE", "同级存在同类型、同名节点", node, "name")
                    seen.add(key)

            for issue in validate_semantic_references(document):
                add(issue.level, issue.code, issue.message, issue.node, issue.field)

            try:
                from src.modeling.interoperability import validate_interoperability
                from src.modeling.scl_serializer import SclModelSerializer

                generated = SclModelSerializer().serialize(project, list(nodes))
                interoperability = validate_interoperability(generated.xml, filename=generated.filename)
                for scl_issue in interoperability["issues"]:
                    add(
                        scl_issue["level"],
                        scl_issue["code"],
                        scl_issue["message"],
                    )
            except Exception as exc:
                add("ERROR", "SCL_SERIALIZATION_FAILED", f"SCL 生成或解析失败：{exc}")

            error_count = sum(issue["level"] == "ERROR" for issue in issues)
            warning_count = sum(issue["level"] == "WARNING" for issue in issues)
            project.validation_errors = error_count
            project.validation_warnings = warning_count
            project.status = "VALID" if error_count == 0 else "DRAFT"
            return {
                "passed": error_count == 0,
                "error_count": error_count,
                "warning_count": warning_count,
                "issues": issues,
                "validated_revision": project.revision,
                "interoperability": interoperability if "interoperability" in locals() else None,
            }

    @staticmethod
    def get_kind_schema(kind: str) -> dict[str, Any]:
        try:
            return get_kind_schema(kind)
        except KeyError as exc:
            raise NotFoundError(f"不支持的节点类型：{kind}") from exc

    @staticmethod
    def _version_dict(version: Iec61850ModelVersion) -> dict[str, Any]:
        return {
            "id": version.id,
            "project_id": version.project_id,
            "version_number": version.version_number,
            "label": version.label,
            "description": version.description,
            "status": version.status,
            "source_revision": version.source_revision,
            "created_at": _iso(version.created_at),
        }

    @staticmethod
    def _build_snapshot(
        project: Iec61850ModelProject,
        document: ModelDocument,
    ) -> dict[str, Any]:
        return {
            "format_version": 1,
            "project": {
                "name": project.name,
                "description": project.description,
                "file_type": project.file_type,
                "standard_version": project.standard_version,
                "namespace": project.namespace,
                "modeling_mode": project.modeling_mode,
            },
            "nodes": [node.to_dict() for node in document.nodes],
            "references": [reference.to_dict() for reference in document.references],
        }

    def _create_version_in_session(
        self,
        session: Session,
        project: Iec61850ModelProject,
        *,
        label: str,
        description: str,
        status: str = "SNAPSHOT",
    ) -> Iec61850ModelVersion:
        document = self._load_document(project)
        next_number = (
            session.scalar(
                select(func.max(Iec61850ModelVersion.version_number)).where(
                    Iec61850ModelVersion.project_id == project.id
                )
            )
            or 0
        ) + 1
        version = Iec61850ModelVersion(
            id=str(uuid.uuid4()),
            project_id=project.id,
            version_number=next_number,
            label=label.strip() or f"版本 V{next_number}",
            description=description.strip(),
            status=status,
            source_revision=project.revision,
            snapshot_json=_json_dumps(self._build_snapshot(project, document)),
        )
        session.add(version)
        session.flush()
        return version

    def list_versions(self, project_id: str) -> list[dict[str, Any]]:
        with self.session_factory() as session:
            self._require_project(session, project_id)
            versions = session.scalars(
                select(Iec61850ModelVersion)
                .where(Iec61850ModelVersion.project_id == project_id)
                .order_by(Iec61850ModelVersion.version_number.desc())
            ).all()
            return [self._version_dict(version) for version in versions]

    @_serialized_project_operation
    def create_version(self, project_id: str, *, label: str = "", description: str = "") -> dict[str, Any]:
        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            version = self._create_version_in_session(
                session,
                project,
                label=label,
                description=description,
            )
            return self._version_dict(version)

    @_serialized_project_operation
    def restore_version(self, project_id: str, version_id: str) -> dict[str, Any]:
        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            version = session.scalar(
                select(Iec61850ModelVersion).where(
                    Iec61850ModelVersion.id == version_id,
                    Iec61850ModelVersion.project_id == project_id,
                )
            )
            if not version:
                raise NotFoundError("模型版本不存在")
            snapshot = _json_loads(version.snapshot_json)
            if snapshot.get("format_version") != 1:
                raise ValidationError("不支持的模型快照格式")

            project_data = snapshot.get("project") or {}
            for key in ("name", "description", "file_type", "standard_version", "namespace", "modeling_mode"):
                if key in project_data:
                    setattr(project, key, project_data[key])
            document = ModelDocument.empty(project_id)
            for item in snapshot.get("nodes") or []:
                document.add_node(
                    node_id=item["id"],
                    parent_id=item.get("parent_id"),
                    kind=item["kind"],
                    name=item["name"],
                    sort_order=int(item.get("sort_order", 0)),
                    attributes=item.get("attributes"),
                    revision=int(item.get("revision", 1)),
                )
            document.references = [
                ModelReference(
                    id=item["id"],
                    source_node_id=item["source_node_id"],
                    target_node_id=item["target_node_id"],
                    relation_type=item["relation_type"],
                    attributes=dict(item.get("attributes") or {}),
                )
                for item in snapshot.get("references") or []
            ]
            self._save_document(project, document)
            project.revision += 1
            project.status = "DRAFT"
            return {
                "restored_version": self._version_dict(version),
                "project_revision": project.revision,
                "node_count": len(snapshot.get("nodes") or []),
            }

    @_serialized_project_operation
    def delete_version(self, project_id: str, version_id: str) -> None:
        with self.session_factory() as session, session.begin():
            self._require_project(session, project_id)
            version = session.scalar(
                select(Iec61850ModelVersion).where(
                    Iec61850ModelVersion.id == version_id,
                    Iec61850ModelVersion.project_id == project_id,
                )
            )
            if not version:
                raise NotFoundError("模型版本不存在")
            if version.status == "PUBLISHED":
                raise ValidationError("已发布版本不可删除")
            session.delete(version)

    @_serialized_project_operation
    def generate_scl(self, project_id: str, *, file_type: str | None = None) -> dict[str, Any]:
        from src.modeling.scl_serializer import SclModelSerializer

        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            nodes = self._load_document(project).nodes
            target_file_type = (file_type or project.file_type).upper()
            variant_issues = validate_file_variant(nodes, target_file_type, for_publish=False)
            if variant_issues:
                raise ValidationError("目标 SCL 文件变体不满足生成契约", {"issues": variant_issues})
            result = SclModelSerializer().serialize(project, nodes, file_type=target_file_type)
            return {
                "xml": result.xml,
                "filename": result.filename,
                "size": len(result.xml.encode("utf-8")),
                "revision": project.revision,
                "status": project.status,
            }

    @_serialized_project_operation
    def generate_artifact_bundle(self, project_id: str, *, file_type: str | None = None) -> dict[str, Any]:
        from src.modeling.scl_serializer import SclModelSerializer

        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            nodes = self._load_document(project).nodes
            target_file_type = (file_type or project.file_type).upper()
            variant_issues = validate_file_variant(nodes, target_file_type, for_publish=False)
            if variant_issues:
                raise ValidationError("目标 SCL 文件变体不满足生成契约", {"issues": variant_issues})
            scl = SclModelSerializer().serialize(project, nodes, file_type=target_file_type)
            bundle = build_artifact_bundle(project, nodes, scl.xml, scl.filename)
            return {
                "content": bundle.content,
                "filename": bundle.filename,
                "size": len(bundle.content),
                "manifest": bundle.manifest,
                "artifacts": [artifact.metadata() for artifact in bundle.artifacts],
                "revision": project.revision,
            }

    @_serialized_project_operation
    def publish_project(self, project_id: str, *, label: str = "", description: str = "") -> dict[str, Any]:
        validation = self.validate_project(project_id)
        if not validation["passed"]:
            raise ValidationError("模型校验未通过，不能发布", validation)
        from src.modeling.interoperability import xsd_required_for_publish

        xsd = (validation.get("interoperability") or {}).get("xsd") or {}
        if xsd_required_for_publish() and xsd.get("status") != "PASSED":
            raise ValidationError(
                "当前环境要求通过官方 SCL XSD 后才能发布",
                {"xsd": xsd},
            )
        with self.session_factory() as session:
            project = self._require_project(session, project_id)
            nodes = self._load_document(project).nodes
            variant_issues = validate_file_variant(nodes, project.file_type, for_publish=True)
            if variant_issues:
                raise ValidationError("当前文件变体不能发布", {"issues": variant_issues})
        generated = self.generate_artifact_bundle(project_id)
        with self.session_factory() as session, session.begin():
            project = self._require_project(session, project_id)
            session.execute(
                Iec61850ModelVersion.__table__.update()
                .where(
                    Iec61850ModelVersion.project_id == project_id,
                    Iec61850ModelVersion.status == "PUBLISHED",
                )
                .values(status="SNAPSHOT")
            )
            version = self._create_version_in_session(
                session,
                project,
                label=label or f"发布版本 r{project.revision}",
                description=description,
                status="PUBLISHED",
            )
            project.status = "PUBLISHED"
            scl_artifact = next(item for item in generated["artifacts"] if item["kind"] == "SCL")
            return {
                "version": self._version_dict(version),
                "validation": validation,
                "artifact": {**scl_artifact, "revision": generated["revision"]},
                "bundle": {key: generated[key] for key in ("filename", "size", "revision")},
                "manifest": generated["manifest"],
            }
